// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title IVerifier - Interface for ZK-SNARK verifier
/// @author Glacier
/// @notice Interface for verifier contracts generated by circom
interface IVerifier {
    /// @notice Verifies a ZK-SNARK proof
    /// @param proof Serialized proof
    /// @param pubSignals Public signals from the circuit
    /// @return true if the proof is valid
    function verifyProof(
        bytes calldata proof, 
        uint256[] calldata pubSignals
    ) external view returns (bool);
}